# Generated by Django 2.2.2 on 2019-07-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190724_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('rollno', models.CharField(max_length=111)),
                ('phone', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=111)),
            ],
        ),
    ]
