# Generated by Django 2.2.2 on 2019-07-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quan',
            field=models.CharField(default='', max_length=10),
        ),
    ]
